spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  spring:
    datasource:
      url: jdbc:mysql://localhost/test?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      password: root

server:
  port: 8000
